[fabric] Ansible decoupling for chaincode ops
hyperledger/bevel pull request #1896
Opened 2022-03-22 13:02 UTC by mgCepeda

Signed-off-by: mgCepeda <marina.gomez.cepeda@accenture.com>

**Changelog**
- Add new yaml files in rol create/ca-tools
- Fix small bug in role delete/vault_secrets
- Update create/k8s_secrets, create/ca-tools, /create/chaincode/commit, create/chaincode/install, create/chaincode/invoke roles and /charts/commit_chaincode, /charts/install_chaincode/ charts

 

**Reviewed by**
@suvajit-sarkar 
@jagpreetsinghsasan 

 

**Linked issue**
#1720

2022-03-23 06:26 UTC, jagpreetsinghsasan requested changes

2022-03-23 06:26 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/charts/commit_chaincode/templates/commit_chaincode.yaml
> +          formatCertificate () {
Very good 👍 👍 👍

2022-03-23 06:26 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/write.yaml
> +  shell: |
This task should be done by pulling the certificate from vault and not using `kubectl cp` cmd

2022-03-23 06:26 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/write.yaml
> +  shell: |
This task should be done by pulling the certificate from vault and not using `kubectl cp` cmd

2022-03-23 06:26 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
> +    - organization:
Write a comment here saying `Only one peer per org required for endorsement`

2022-03-23 06:26 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
> +      name: carrier
Write a comment here saying `Only one peer per org required for endorsement`

2022-03-23 06:26 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-ordererorg.yaml
> +      name: carrier
Write a comment here saying `Only one peer per org required for endorsement`

2022-03-23 06:26 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
> +    - organization:
Write a comment here saying `Only one peer per org required for endorsement`

2022-03-23 06:26 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
> +    - organization:
Write a comment here saying `Only one peer per org required for endorsement`

2022-03-24 09:05 UTC, jagpreetsinghsasan approved these changes

2022-03-25 15:01 UTC, sownak approved these changes

2022-03-25 15:01 UTC, merged