[fabric]  Add orderer/peer update
hyperledger/bevel pull request #1956
Opened 2022-05-24 15:54 UTC by mgCepeda

Signed-off-by: mgCepeda <marina.gomez.cepeda@accenture.com>

**Changelog**

- Update platforms/hyperledger-fabric/configuration/add-orderer.yaml and platforms/hyperledger-fabric/configuration/add-peer.yaml: 

 

**Reviewed by**
@suvajit-sarkar
@jagpreetsinghsasan

 

**Linked issue**
#issue_number

2022-05-25 07:39 UTC, jagpreetsinghsasan commented
@mgCepeda Please add the issue number in this PR description.

2022-05-25 07:43 UTC, jagpreetsinghsasan requested changes

2022-05-25 07:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
> +- name: Copy the msp admincerts from vault
Please rename the task and the above comment to `Fetch the msp admincerts from vault`

2022-05-25 07:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
> +- name: Copy the msp cacerts from vault
Please rename the task and the above comment to `Fetch the msp cacerts from vault`

2022-05-25 07:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
> +- name: Copy the msp tlscacerts from vault
Please rename the task and the above comment to `Fetch the msp tlscacerts from vault`

2022-05-25 07:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
> +- name: Copy the msp cacerts from vault
Please rename the task and the above comment to `Fetch the msp cacerts from vault`

2022-05-25 07:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
> +- name: Copy the msp tlscacerts from vault
Please rename the task and the above comment to `Fetch the msp tlscacerts from vault`

2022-05-25 07:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
> +- name: Copy the tls server.crt from vault
Please rename the task and the above comment to `Fetch the tls server.crt from vault`

2022-05-25 07:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
> +- name: Copy the tls ca.crt file from vault
Please rename the task and the above comment to `Fetch the tls ca.crt from vault`

2022-05-25 07:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml
> +- name: Copy the msp admincerts from vault
Make all such statements as "Fetch from vault"

2022-05-25 07:43 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/users/tasks/main.yaml
> +- pause:
Do we need this?

2022-05-26 11:34 UTC, jagpreetsinghsasan approved these changes
LGTM

2022-05-26 11:35 UTC, jagpreetsinghsasan commented
@mgCepeda can you squash merge the commits?

2022-05-26 11:35 UTC, jagpreetsinghsasan commented
Rest everything looks good to me.

2022-05-26 11:45 UTC, suvajit-sarkar approved these changes

2022-05-26 11:48 UTC, merged