[fabric] Certificate refresh
hyperledger/bevel pull request #1999
Opened 2022-07-29 12:32 UTC by mgCepeda

Signed-off-by: mgCepeda <marina.gomez.cepeda@accenture.com>

**Changelog**
- Add the operation to refresh the certificates
- Fix image names and variable names in examples/supplychain-app/configuration/roles/create/fabric/expressapi/tasks/main.yaml, examples/supplychain-app/configuration/roles/helm_component/templates/restserver.tpl and examples/ supplychain-app/configuration/roles/helm_component/templates/webserver-cordaent.tpl for supplychain deployment to work with ghcr.io/hyperledger

The certificate rotation process has been carried out using this guide:
https://medium.com/coinmonks/certification-rotation-in-hyperledger-fabric-c9eb5fc68dec

 

**Reviewed by**
@suvajit-sarkar @jagpreetsinghsasan 

 

**Linked issue**
#1429

2022-08-01 14:50 UTC, sownak approved these changes

2022-08-08 07:16 UTC, jagpreetsinghsasan requested changes

2022-08-08 07:16 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/get_update_block.yaml
> +- name: fetch {{ channel_name }} configuration block from the blockchain
Please make the first letter capital, so that it looks similar to other tasks

2022-08-08 07:16 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/get_update_block.yaml
> +- name: modify, update and copy {{ channel_name }} configuration block from the blockchain
Please make the first letter capital, so that it looks similar to other tasks

2022-08-08 07:16 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/get_update_block.yaml
> +- name: fetch the latest block from the blockchain
Please make the first letter capital, so that it looks similar to other tasks

2022-08-08 07:16 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/main.yaml
> +- name: "delete all temp {{ orderer.name }}-{{ org.name }}-cli"
Please make the first letter capital, so that it looks similar to other tasks

2022-08-08 07:16 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/nested_create_cli.yaml
> +- name: "create valuefile for cli {{ orderer.name }}-{{ org.name }}"
Please make the first letter capital, so that it looks similar to other tasks

2022-08-08 07:16 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/nested_create_cli.yaml
> +- name: "Check if fabric cli is present"
Rename this to : Wait for the fabric cli to come up

2022-08-08 07:16 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/nested_create_cli.yaml
> +- name: "start cli"
Please make the first letter capital, so that it looks similar to other tasks

2022-08-08 07:16 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/nested_create_cli.yaml
> +  shell: |
If we are starting a new cli for certain tasks, make sure to remove them after the task is completed

2022-08-08 07:16 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/nested_create_cli.yaml
> +- pause:
Why do we need this pause?

2022-08-18 10:15 UTC, suvajit-sarkar approved these changes

2022-08-22 02:20 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/nested_create_cli.yaml
> +  shell: |
@mgCepeda you can click on `Resolve conversation` once you have fixed the review comments.

2022-08-22 02:21 UTC, jagpreetsinghsasan approved these changes

2022-08-22 02:22 UTC, jagpreetsinghsasan commented
LGTM, just the rebase of the @mgCepeda required.

2022-08-22 10:35 UTC, merged