Upgrade deployment to 2.2.x
hyperledger/bevel pull request #2050
Opened 2022-10-28 07:31 UTC by Mohitv

**Changelog**
- Add : Upgrade deployment of Hypeledger Fabric deployment to 2.2.x. The documentation is available in docs folder at /docs/source/operations/upgrade_fabricnetwork_1.4.x_2.2.2.md
- Fix
- Update

 

**Reviewed by**
@sownak @jagpreetsinghsasan 

 

**Linked issue**
#issue_number

2022-10-31 05:57 UTC, jagpreetsinghsasan commented
@Mohitv another huge commits.
Once you create a PR using a branch, please do not use that branch to do anymore work involving pushing of such commits. Received 81 mails for 81 commits

2022-10-31 06:06 UTC, Mohitv commented
> @Mohitv another PR with huge number of commits. Once you create a PR using a branch, please do not use that branch to do anymore work involving pushing of such commits. Received 81 mails for 81 commits

@jagpreetsinghsasan I was not aware of this and was testing on my branch for the demo. If possible please cancel this PR and I will create a new

2022-11-02 10:10 UTC, sownak commented
Please check https://github.com/hyperledger/bevel/blob/main/CONTRIBUTING.md. 
There is a conflict, that needs to be resolved.

2022-11-03 06:07 UTC, jagpreetsinghsasan requested changes
There are repeating review comments (many places I havent even mention them as they are so many, but very small ones).
Also certain files like reset.sh, git_push task are empty which is required to be fixed.

2022-11-03 06:07 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/upgrade/orderer-binary/tasks/create_orderer_value.yaml
> +- name: Git Status
This is not required. Also, I see you registered the output of this task to `git_result` and in the very next task also, the registered variable is `git_result` which is useless

2022-11-03 06:07 UTC, jagpreetsinghsasan commented on platforms/hyperledger-fabric/configuration/roles/upgrade/peer-binary/tasks/create_peer_value.yaml
> +- name: Git Status
Same comment for the git status task as mentioned previously.

2022-11-03 06:07 UTC, jagpreetsinghsasan commented on platforms/shared/configuration/roles/git_status/Readme.md
> +[//]: # (##############################################################################################)
Not required

2022-11-03 06:07 UTC, jagpreetsinghsasan commented on platforms/shared/configuration/roles/git_status/tasks/main.yaml
> +##############################################################################################
Not required

2022-11-03 06:07 UTC, jagpreetsinghsasan commented on platforms/shared/configuration/roles/check/helm_component/tasks/main.yaml
> +
Newline at EOF

2022-11-14 04:27 UTC, Mohitv commented on platforms/hyperledger-fabric/configuration/roles/upgrade/add-app-channel-acls/tasks/main.yaml
> +- name: Ensure channel-artifacts dir exists
I have kept only 2 tasks, First will remove and second will create a new folder. I have tested the first and it does not throw error if directory does not exists

2022-11-14 04:27 UTC, Mohitv commented on platforms/hyperledger-fabric/configuration/roles/upgrade/add-app-channel-acls/tasks/main.yaml
> +  when: acls_file.stat.exists
done. here and all other instance mentioned in reviews

2022-11-14 04:27 UTC, Mohitv commented on platforms/hyperledger-fabric/configuration/roles/upgrade/add-app-channel-acls/tasks/sign_block.yaml
> +- name: "Check if fabric cli is present"
done. here and all other instance mentioned in reviews below

2022-11-15 07:15 UTC, jagpreetsinghsasan commented
Closing this PR as a new one has been created here #2069

2022-11-15 07:15 UTC, closed without merging