sample
hyperledger/bevel pull request #2053
Opened 2022-11-02 09:32 UTC by charry1729

**Changelog**
- Add
- Fix
- Update

 

**Reviewed by**
@developer_github_id

 

**Linked issue**
#issue_number

2022-11-02 10:10 UTC, sownak commented
Please check https://github.com/hyperledger/bevel/blob/main/CONTRIBUTING.md

2022-11-09 05:50 UTC, jagpreetsinghsasan requested changes
There are a lot of more files to be reviewed. Please cleanup the code, add incode comments, remove unwanted commented code as soon as possible, we have very little time left for this.

Also, `let this PR be in draft phase until said so` because there are hundreds of commits, improper contributing guidelines; all of these should be fixed in the draft PR itself before creating the final `good-to-go` PR

2022-11-09 05:50 UTC, jagpreetsinghsasan commented on platforms/hyperledger-besu/charts/node_besu/templates/deployment.yaml
> +            --Xdns-update-enabled=true \z
What is this `z` for?

2022-11-09 05:50 UTC, jagpreetsinghsasan commented on platforms/shared/charts/besu-connector/templates/configmap.yaml
> +    }
Please add a new line here

2022-11-09 05:50 UTC, jagpreetsinghsasan commented on platforms/shared/charts/besu-connector/templates/deployment.yaml
> +  # serviceName: {{ .Values.service.name }}
Please remove unwanted commented code everywhere

2022-11-09 05:50 UTC, jagpreetsinghsasan commented on platforms/shared/charts/besu-connector/templates/service.yaml
> +  # version: '1'
Connectors will generally stay outside the ledger environment, thus having ambassador mappings is must

2022-11-09 05:50 UTC, jagpreetsinghsasan commented on platforms/shared/charts/besu-connector/values.yaml
> +metadata:
Please add in-line comments for each `key:value` pair

2022-11-09 05:50 UTC, jagpreetsinghsasan commented on platforms/shared/charts/fabric-connector/templates/configmap.yaml
> +
Please do a cleanup of unwanted commented code or newlines

2022-11-09 05:50 UTC, jagpreetsinghsasan commented on platforms/shared/charts/fabric-connector/templates/configmap.yaml
> +    "packageName": {{ .Values.plugins.packageName | quote }},
Please have proper tabs and spacings for this json config

2023-03-02 12:59 UTC, sownak commented
This is not a valid request and the changes will be incorporated in a separate PR that I have worked upon.

2023-03-02 12:59 UTC, closed without merging