Skip ambassador installation when installed
hyperledger/bevel pull request #2128
Opened 2023-01-22 11:50 UTC by adityajoshi12

**Changelog**
This PR has changeset for skipping ambassador installation when it's installed. Optionally, now namespace can also be provided when installing the ambassador.

 

**Reviewed by**
@developer_github_id

 

**Linked issue**
#2111

2023-01-23 05:56 UTC, jagpreetsinghsasan requested changes
We shouldn't skip ambassador installation this simply.
There can be scenarios when there are 2 deployments using the same ambassador, but one ambassador is using a port range from 15010-15020 and then another deployment want to use next 10 ports (so they can simply mention 15010-15030 and ambassador will open those 10 more ports).
Either we check the opened ports are same as well to skip ambassador installation or we just include the namespaced proxy installation feature of this PR.

2023-01-23 05:56 UTC, jagpreetsinghsasan commented on platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml
> +    kubeconfig: { { kubeconfig_path } }
Please rename this to ``{{ kubeconfig_path }}`` and similarly to the next line var

2023-01-23 06:00 UTC, jagpreetsinghsasan commented
Also, try to use the [newer format](https://github.com/hyperledger/bevel/blob/develop/.github/pull_request_template.md) for PR message (and similarly the commit message) (most likely you will start receiving the new PR format once the develop branch is merged into main).

2023-01-28 14:35 UTC, adityajoshi12 commented
> We shouldn't skip ambassador installation this simply. There can be scenarios when there are 2 deployments using the same ambassador, but one ambassador is using a port range from 15010-15020 and then another deployment want to use next 10 ports (so they can simply mention 15010-15030 and ambassador will open those 10 more ports). Either we check the opened ports are same as well to skip ambassador installation or we just include the namespaced proxy installation feature of this PR.

Thanks for the suggestion, made the changes as per the suggestion. We are now checking if the ports are already opened in the existing installation. if they are found to be present then skip installation else the ambassador.

2023-01-30 02:39 UTC, jagpreetsinghsasan requested changes
There are still some inconsistencies within the code.
It does certain operations only when `no ambassador_installed`, for example: the task `Format ambassador ports`. This should still format ports, even if ambassador is installed.

Also once fixed, please create an issue to address this update in other platforms also (one issue to mention that we need to update this for fabric, corda, quorum, indy), so that we can have a track of it.

2023-02-07 05:55 UTC, jagpreetsinghsasan commented
@adityajoshi12 I saw you added commit(s) after my last review. If you think its ready for review again, you should re-request for review 
![image](https://user-images.githubusercontent.com/56861721/217160310-3591303f-60a2-43f2-8090-cf73a75ec729.png)

2023-02-07 12:12 UTC, jagpreetsinghsasan approved these changes
LGTM, thankyou!

2023-02-07 12:12 UTC, jagpreetsinghsasan commented on platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml
> +    - ambassador_installed
Please have a space between tasks

2023-02-10 08:58 UTC, suvajit-sarkar commented on platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml
> +    - ambassador_installed
@adityajoshi12 kindly have a look

2023-02-10 09:17 UTC, adityajoshi12 commented on platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml
> +    - ambassador_installed
@suvajit-sarkar updated...

2023-02-17 11:24 UTC, merged