[shared] workflow for alpine1.1 image
hyperledger/bevel pull request #2148
Opened 2023-02-10 11:12 UTC by RaviKiranJanjanam

Signed-off-by: RaviKiranJanjanam <ravi.kiran.janjanam@accenture.com>

**Changelog**

Added the workflow for alpine-image:1.1
fixed the repository name to be in lowercase for below files under workflow

.github/workflows/corda_images_build.yml
.github/workflows/docker_build.yml
.github/workflows/indy_image_build.yaml
.github/workflows/quorum_images_build.yml

 

**Reviewed by**
@sownak @suvajit-sarkar @jagpreetsinghsasan 

 

**Linked issue**
#2147

2023-02-15 11:31 UTC, suvajit-sarkar requested changes

2023-02-15 11:31 UTC, suvajit-sarkar commented on .github/workflows/alpine_image.yaml
> +        tags: ${{ steps.image_path_format.outputs.lowercase }}/alpine-utils:1.1
the tag should be based on the release tag for releases, latest for develop branch push

2023-02-15 11:31 UTC, suvajit-sarkar commented on .github/workflows/alpine_image.yaml
> +# Build bevel-build docker image triggered by :
Change comments

2023-02-15 11:36 UTC, suvajit-sarkar commented
Kindly check the acceptance criterion https://github.com/hyperledger/bevel/issues/2147

2023-02-21 06:46 UTC, jagpreetsinghsasan requested changes
1. Is this tested for all the platforms? (As this will affect them all)
2. This PR should change all instances of alpine image usages in all platforms to strictly use `1.1` instead of `1.0` or `latest`
3. What is env.IMAGE_PATH in this (exact value)? (To understand why are we making it lowercase everywhere)

2023-02-21 06:46 UTC, jagpreetsinghsasan commented on platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/crypto_tessera.tpl
> +      alpineutils: "{{ network.docker.url }}/alpine-utils:{{ network.bevel_version | default('latest') }}"
This should not be changed as `network.bevel_version` gives a wrong sense of information that by changing to lets say, `1.0` version, will indeed make use of Bevel 1.0 code.
Bevel versions are heavily affected by code changes and the right way to use a specific version of Bevel is via changing the `tag` of the local Bevel repo (from where the deployments are made).

2023-02-21 06:46 UTC, jagpreetsinghsasan commented on .github/workflows/alpine_image.yaml
> +name: Build alpine1.1 Docker image and push
This should be renamed to `Build alpine docker image and push to ghcr`

2023-02-21 06:46 UTC, jagpreetsinghsasan commented on .github/workflows/alpine_image.yaml
> +        tags: ${{ steps.image_path_format.outputs.lowercase }}/alpine-utils:latest
We should not use `latest` tag here and specifically mention the `1.1` version

2023-02-27 11:31 UTC, suvajit-sarkar commented
I'm resolving the conversation and closing this PR

2023-02-27 11:33 UTC, merged