bevel fabric - minikube setup
hyperledger/bevel pull request #2164
Opened 2023-02-26 16:26 UTC by Mohitv

**Changelog**
Add Minikube documentation
Fix to deploy HF fabric on minikube
 

**Reviewed by**
@jagpreetsinghsasan

 

**Linked issue**
#1796

2023-02-27 06:08 UTC, jagpreetsinghsasan commented on docs/source/developer/bevel_fabric_minikube_setup.md
> +1. Please setup a Ubuntu 20.04 VM with atleast 16 GB RAM, 8 vcpu and having a public ip address, on any cloud provider like Azure, GCP etc. How to set and get a public ip address of VM, one needs to
For the first step, one could use their own local machine to setup minikube. Can we seperate this into 2 points, 1.1) Getting public IP of local machine and 1.2) Setup on cloud and get the instance public IP

2023-02-27 06:08 UTC, jagpreetsinghsasan requested changes
Rest all looks good to me

2023-03-03 11:07 UTC, sownak commented
@Mohitv Can the last comment be addressed please?

2023-03-05 04:18 UTC, Mohitv commented
@sownak @jagpreetsinghsasan I have updated the feedback. Kindly check

2023-03-07 10:36 UTC, sownak approved these changes

2023-03-08 04:59 UTC, merged