Updated contribution.md with create local branch & directory structure
hyperledger/bevel pull request #2201
Opened 2023-04-06 08:17 UTC by maheshkasabe

2023-04-06 09:22 UTC, adityajoshi12 reviewed
Please refer https://github.com/hyperledger/bevel/blob/main/CONTRIBUTING.md

2023-04-09 14:26 UTC, suvajit-sarkar commented
kindly sign your commits, DCO lint failing

2023-04-10 04:26 UTC, adityajoshi12 commented
Please refer contribution guide https://github.com/hyperledger/bevel/blob/main/CONTRIBUTING.md
Also, PR should be for develop branch

2023-04-11 04:27 UTC, jagpreetsinghsasan requested changes
There are certain points I would like to highlight here
1. Please make sure to squash merge commits into 1
2. Please add the PR description (the PR description template auto populates, which I think you have removed)

Points 1, 2 and some more improvements and mentions are required even for the contributing guide issue #2131 , but as this PR only focuses on adding the docs for creating local branches and explaining the basic folder structure, its fine.

2023-04-11 04:27 UTC, jagpreetsinghsasan commented on CONTRIBUTING.md
> +Whenever you begin to use your codes on Hyperledger Bevel, you should follow the directory strecture on Hyperledger Bevel.
`strecture` typo

2023-04-11 16:40 UTC, closed without merging