[ci-skip] Ansible decoupling for create/users
hyperledger/bevel pull request #2216
Opened 2023-04-18 07:08 UTC by mgCepeda

Primary Changes
--------------
1. updated ca-tools chart
2. updated ca-tool tpl file
3. updated platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer role
4. Deleted platforms/hyperledger-fabric/configuration/roles/create/users role

Modifications in roles and tpl files
-----------------------
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/Readme.md platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml platforms/hyperledger-fabric/configuration/roles/create/users/Readme.md platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-tools.tpl

Modifications in charts
-------------------------
platforms/hyperledger-fabric/charts/catools/templates/configmap.yaml platforms/hyperledger-fabric/charts/catools/templates/deployment.yaml platforms/hyperledger-fabric/charts/catools/values.yaml

2023-04-21 07:03 UTC, jagpreetsinghsasan requested changes

2023-04-24 06:22 UTC, mgCepeda commented on platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-tools.tpl
> +      secretusers: {{ vault.secret_path | default('secretsv2') }}/data/crypto/{{ component_type }}Organizations/{{ component_name }}/users
We currently use secretsv2 on all platforms as default

2023-04-25 03:48 UTC, jagpreetsinghsasan approved these changes
Changes incorporated. Looks good to me for the merge.

2023-04-25 08:28 UTC, sownak approved these changes

2023-04-25 08:28 UTC, merged