[besu] Add extradata field in genesis file - QBFT consensus
hyperledger/bevel pull request #2236
Opened 2023-05-10 12:46 UTC by mgCepeda

Primary Changes
--------------
1. Added extradata field in genesis file. platforms/hyperledger-besu/configuration/roles/create/genesis/qbft role
2. Added templates to create genesis file

Modifications in roles and tpl files
-----------------------
platforms/hyperledger-besu/configuration/roles/create/genesis/qbft/tasks/main.yaml 
platforms/hyperledger-besu/configuration/roles/create/genesis/qbft/templates/qbftGenesisFile.tpl platforms/hyperledger-besu/configuration/roles/create/genesis/qbft/templates/qbftPermissionGenesisFile.tpl

Fixes
#2233

2023-05-10 12:53 UTC, suvajit-sarkar approved these changes
LGMT

2023-05-10 14:23 UTC, sownak requested changes

2023-05-10 14:23 UTC, sownak commented on platforms/hyperledger-besu/configuration/roles/create/genesis/qbft/templates/qbftPermissionGenesisFile.tpl
> +      "code": "608060405234801561001057600080fd5b506004361061009e5760003560e01c8063936421d511610066578063936421d5146101ca578063a43e04d8146102fb578063de8fa43114610341578063e001f8411461035f578063fe9fbb
Do we need these smartcontracts in the genesis file by default?

2023-05-11 12:12 UTC, sownak approved these changes

2023-05-11 12:12 UTC, merged