[ci-skip]: add 'none' as a new option for transaction manager on the Quorum platform.
hyperledger/bevel pull request #2238
Opened 2023-05-12 12:09 UTC by saurabhkumarkardam

### **Commit to be reviewed**
---
feat(quorum): add 'none' as a new option for transaction manager.

```
Updated the following files to introduce the new option for transaction manager:
  1. deployment.yaml file of chart node_quorum_member.
  2. memberquorum.tpl template.
  3. deploy-network.yaml file.
  4. network-schema.json.
  5. sample network-quorum.yaml file.

In addition, added a label to the job.yaml files of the following charts:
  1. certs-ambassador-quorum.
  2. crypto_ibft.
  3. crypto_raft.
  4. tessera_key_mgmt.
```

fixes #2234

2023-05-12 14:18 UTC, sownak requested changes

2023-05-12 14:18 UTC, sownak commented on platforms/quorum/configuration/deploy-network.yaml
> +  - name: Print transaction manager configuration
please remove debug statement

2023-05-12 14:18 UTC, sownak commented on platforms/quorum/charts/node_quorum_member/templates/deployment.yaml
> +          if [ -n "$ptm_url" ]
Please use if [ {{ $.Values.tm.type }} != "none" ] condition here as well

2023-05-15 06:19 UTC, jagpreetsinghsasan approved these changes
Looks good to me (previous review comments seem to be incorporated)

2023-05-15 06:37 UTC, suvajit-sarkar commented on platforms/quorum/charts/crypto_raft/templates/job.yaml
> +    app: "{{ $.Values.metadata.name }}"
remove duplicate app labels

2023-05-15 09:24 UTC, sownak approved these changes

2023-05-15 14:16 UTC, merged