[ci-skip] Added readme's for all the helm charts
hyperledger/bevel pull request #2304
Opened 2023-06-23 05:37 UTC by saikumarbommakanti

docs(indy): Added readme's for all the helm charts for platform indy

Add readme files for all charts
Add _helpers.tpl files for all charts
fixes #2288

2023-06-23 11:14 UTC, sownak requested changes
Add newlines in helper.tpl. Update Chart.yaml with new description and version.

2023-06-23 11:14 UTC, sownak commented on platforms/hyperledger-indy/charts/indy-auth-job/templates/_helpers.tpl
> +{{- end }}
Add newline

2023-06-26 09:15 UTC, sownak approved these changes

2023-06-26 12:49 UTC, suvajit-sarkar approved these changes
LGTM

2023-06-26 12:50 UTC, merged