[ci-skip] Add README.md files
hyperledger/bevel pull request #2305
Opened 2023-06-23 11:51 UTC by sailajakommineni

Primary Changes
--------------
1. Add readme files for all charts
2. Update the values.yaml files
3. Update the version in chart.yaml file

Modifications in charts
platforms/r3-corda/charts/doorman-tls
platforms/r3-corda/charts/doorman
platforms/r3-corda/charts/generate-certs
platforms/r3-corda/charts/h2-addUser
platforms/r3-corda/charts/h2-password-change
platforms/r3-corda/charts/h2
platforms/r3-corda/charts/mongodb-tls
platforms/r3-corda/charts/mongodb
platforms/r3-corda/charts/nms-tls
platforms/r3-corda/charts/nms
platforms/r3-corda/charts/node-initial-registration 
platforms/r3-corda/charts/node 
platforms/r3-corda/charts/notary-initial-registration 
platforms/r3-corda/charts/notary platforms/r3-corda/charts/storage

Fixes #2285

2023-06-26 09:18 UTC, sownak requested changes
Also make the descriptions concise. Like no need to add "on Kubernetes" because helm always deploys on Kubernetes and not anywhere else.

2023-06-26 09:18 UTC, sownak commented on platforms/r3-corda/charts/generate-certs/Chart.yaml
> +description: "R3-corda-os: Its generates the certificates for Corda Opensource"
just ": Generates ..."

2023-06-26 09:18 UTC, sownak commented on platforms/r3-corda/charts/h2-addUser/Chart.yaml
> +description: "R3-corda-os: Its authenticate with the Vault server for Corda Opensource"
This chart is not for authenticating use. If this is never used from the roles or playbook, remove these charts

2023-07-11 10:01 UTC, sownak commented on platforms/r3-corda/charts/generate-certs/Chart.yaml
> +description: "R3-corda-os: Generates the ca-certificates for doorman using openssl."
This is not only for doorman

2023-07-11 10:04 UTC, sownak commented on platforms/r3-corda/charts/node-initial-registration/Chart.yaml
> +description: "R3-corda-os: Deploys the job for the initial node registration."
"Job for initial node registration"

2023-07-11 10:05 UTC, sownak commented on platforms/r3-corda/charts/notary-initial-registration/Chart.yaml
> +description: "R3-corda-os: Deploys the job for initial notory node registration."
"Job for initial notary node registration"

2023-07-12 14:33 UTC, sownak requested changes

2023-07-12 14:33 UTC, sownak commented on platforms/r3-corda/charts/node/Chart.yaml
> +description: "R3-corda-os: Deploys the job for r3corda node."
no job involved here

2023-07-12 14:33 UTC, sownak commented on platforms/r3-corda/charts/notary/Chart.yaml
> +description: "R3-corda-os: Deploys the r3corda notory."
notary node

2023-07-13 11:10 UTC, sownak approved these changes

2023-07-17 04:52 UTC, suvajit-sarkar commented on platforms/r3-corda/charts/doorman/Chart.yaml
> +description: "R3-corda-os: Deploys the doorman service for r3corda node."
can you remove the "for r3corda node" part

2023-07-17 04:58 UTC, suvajit-sarkar commented on platforms/r3-corda/charts/mongodb/README.md
> +This [Helm chart](https://github.com/hyperledger/bevel/tree/develop/platforms/r3-corda/charts/mongodb) depolys Mongodb.
typo mistake "deploys"

2023-07-17 04:59 UTC, suvajit-sarkar commented on platforms/r3-corda/charts/mongodb-tls/README.md
> +This [Helm chart](https://github.com/hyperledger/bevel/tree/develop/platforms/r3-corda/charts/mongodb-tls) deploys a MongoDB to enable tls for doorman and networkmap services.
Just say deploys MongoDB with tls enabled

2023-07-17 05:01 UTC, suvajit-sarkar commented on platforms/r3-corda/charts/nms-tls/README.md
> +This [Helm chart](https://github.com/hyperledger/bevel/tree/develop/platforms/r3-corda/charts/nms-tls) deploys the Kubernetes deployment file for a networkmapservice with tls certificate.
change "tls certificate" to "tls enabled"

2023-07-17 05:09 UTC, suvajit-sarkar commented on platforms/r3-corda/charts/nms/README.md
> +This [Helm chart](https://github.com/hyperledger/bevel/tree/develop/platforms/r3-corda/charts/nms) deploys the Kubernetes deployment file for a networkmapservice.
Please make it consistent, compare with how you have written for other charts. You can remove "the Kubernetes deployment file for a". Check across all charts

2023-07-17 05:10 UTC, suvajit-sarkar requested changes
Changes added as comments

2023-07-17 09:11 UTC, suvajit-sarkar approved these changes
LGTM

2023-07-17 09:11 UTC, merged