[ci-skip] Add README.md files
hyperledger/bevel pull request #2324
Opened 2023-07-28 09:15 UTC by sailajakommineni

Primary Changes
--------------
Add readme files for all charts
Update the values.yaml files
Update the version in chart.yaml file

Modifications in charts
---------------------
platforms/r3-corda-ent/charts/auth
platforms/r3-corda-ent/charts/bridge
platforms/r3-corda-ent/charts/float
platforms/r3-corda-ent/charts/gateway
platforms/r3-corda-ent/charts/generate-pki-node
platforms/r3-corda-ent/charts/generate-pki
platforms/r3-corda-ent/charts/h2
platforms/r3-corda-ent/charts/idman
platforms/r3-corda-ent/charts/nmap
platforms/r3-corda-ent/charts/node-initial-registration 
platforms/r3-corda-ent/charts/node
platforms/r3-corda-ent/charts/notary-initial-registration 
platforms/r3-corda-ent/charts/notary
platforms/r3-corda-ent/charts/signer
platforms/r3-corda-ent/charts/zone

Fixes #2284

2023-07-31 05:46 UTC, jagpreetsinghsasan requested changes
There are lots of empty fields, please fix them all

2023-07-31 05:46 UTC, jagpreetsinghsasan commented on platforms/r3-corda-ent/charts/auth/README.md
> +| deployment               | Provide any extra annotations for the deployment                                     | "vaule"         |
`vaule` typo

2023-07-31 09:29 UTC, suvajit-sarkar requested changes

2023-07-31 09:29 UTC, suvajit-sarkar commented on platforms/r3-corda-ent/charts/generate-pki-node/values.yaml
> +  initContainerName:
have default values, check the same for all charts

2023-07-31 09:29 UTC, suvajit-sarkar commented on platforms/r3-corda-ent/charts/generate-pki-node/README.md
> +This [Helm chart](https://github.com/hyperledger/bevel/tree/main/platforms/r3-corda-ent/charts/generate-pki-node) generates the certificates and configure a PKI for node.
generates the corda complaint certificate hierarchy for the node

2023-07-31 09:29 UTC, suvajit-sarkar commented on platforms/r3-corda-ent/charts/generate-pki/Chart.yaml
> +description: "R3-corda-ent: Generates the pki-certificates."
deploys the pki for cenm services

2023-07-31 09:29 UTC, suvajit-sarkar commented on platforms/r3-corda-ent/charts/generate-pki/README.md
> +This [Helm chart](https://github.com/hyperledger/bevel/tree/main/platforms/r3-corda-ent/charts/generate-pki) generates the certificates and configure a PKI for a CENM application.
deploys the pki to generate the corda complaint certificate hierarchy for the CENM services

2023-08-14 10:01 UTC, suvajit-sarkar requested changes
Rest is fine

2023-08-14 10:01 UTC, suvajit-sarkar commented on platforms/r3-corda-ent/charts/generate-pki-node/Chart.yaml
> +description: "R3-corda-ent: deploys the pki."
capital 'D' for deploys

2023-08-14 10:44 UTC, suvajit-sarkar approved these changes
LGTM

2023-08-14 10:45 UTC, merged