[Fabric] move hashicorp vault functions to a single script
hyperledger/bevel pull request #2344
Opened 2023-08-14 10:23 UTC by saurabhkumarkardam

### **Commit to be reviewed**

**feat(fabric): move hashicorp vault functions to a single script**

```
This commit decouples the vault related functionality from individual helm charts by utilizing the bevel-vault.sh script.

Changes made:

 • Removed vault-related code from individual Fabric Helm charts.
 • Updated all Helm charts to utilize the shared bevel-vault.sh script.
 • Deleted the vault_kubernetes_job.tpl template file from Fabric platform as we already move this feature to the shared platform.
 • Deleted the verify_chaincode Helm chart from Fabric platform as it is not in use and also there is no .tpl template file for the same Helm chart.

These changes will improve code maintainability and efficiency by reducing code duplication and making it easier to maintain consistency.
```

fixes #2323

2023-08-15 08:12 UTC, sownak requested changes
rest looks good

2023-08-15 08:12 UTC, sownak commented on platforms/hyperledger-fabric/charts/ca/templates/deployment.yaml
> +      {{ if .Values.vault.tls  }} # true
these comments are not right

2023-08-16 04:41 UTC, saurabhkumarkardam commented on platforms/hyperledger-fabric/charts/ca/templates/deployment.yaml
> +      {{ if .Values.vault.tls  }} # true
Corrections have been made. Thank you.

2023-08-16 08:33 UTC, sownak approved these changes

2023-08-16 10:50 UTC, suvajit-sarkar approved these changes
LGTM

2023-08-16 10:50 UTC, merged