[shared] enable OS-specific command handling in helm charts
hyperledger/bevel pull request #2388
Opened 2023-10-17 05:49 UTC by saurabhkumarkardam

### **Commit to be reviewed**
---
**feat(shared): enable OS-specific command handling in helm charts**

```
This PR improves the handling of OS-specific commands within Helm charts.

Changes:
- Introduced a script to check the Operating System and its supporting package manager for efficient package installation.
- Added a ConfigMap object to insert the same above-mentioned script into the container, improving flexibility and compatibility.

Additional change:
- Updated the StorageClass Helm chart to resolve the node affinity issue.

There are only 3 platforms that are currently using OS-Specific Command in Helm Charts directly, and this PR is also made for these 3 platforms only:
- Quorum
- Hyperledger-Fabric
- Substrate
```

fixes #2366

2023-10-17 06:07 UTC, jagpreetsinghsasan commented
Where is the `bevel-vault.sh` script located in our repo?

2023-10-17 06:15 UTC, saurabhkumarkardam commented
> @saurabhkumarkardam where is the `bevel-vault.sh` script located in our repo?

platforms/shared/charts/bevel-scripts/scripts/bevel-vault.sh

2023-10-17 08:47 UTC, sownak requested changes
just rename packet to package

2023-10-17 08:47 UTC, sownak commented on platforms/hyperledger-fabric/charts/catools/templates/deployment.yaml
> +      - name: packet-manager
Please rename to 'package-manager'

2023-10-17 08:47 UTC, sownak commented on platforms/hyperledger-fabric/charts/generate_cacerts/templates/job.yaml
> +              . /scripts/packet-manager.sh
rename

2023-10-17 09:27 UTC, saurabhkumarkardam commented on platforms/hyperledger-fabric/charts/catools/templates/deployment.yaml
> +      - name: packet-manager
Fixed. Please review.

2023-10-17 09:27 UTC, saurabhkumarkardam commented on platforms/hyperledger-fabric/charts/generate_cacerts/templates/job.yaml
> +              . /scripts/packet-manager.sh
Fixed. Please review.

2023-10-18 13:20 UTC, sownak approved these changes

2023-10-19 10:38 UTC, suvajit-sarkar approved these changes
LGTM

2023-10-19 10:38 UTC, merged