Moving Aries Agent charts from Hyperledger Labs to Bevel
hyperledger/bevel pull request #2501
Opened 2024-01-30 22:34 UTC by monar24

Our team at superlogic proposed a hyperledger lab for our aries-agent charts. We were asked to raise a PR for contributing this part to Bevel. Previous conversation may be viewed here: https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/259

2024-01-31 12:37 UTC, suvajit-sarkar approved these changes
LGTM

2024-01-31 13:51 UTC, sownak requested changes
How is multi-cloud supported?

2024-01-31 13:51 UTC, sownak commented on platforms/hyperledger-aries/chart/values.yaml
> +  image:
can we use `image.repository` and `image.tag` format for the images

2024-01-31 13:51 UTC, sownak commented on platforms/hyperledger-aries/chart/values.yaml
> +ingress:
Bevel calls ingress and proxy, so can this be moved to key called `global.proxy`

2024-02-02 11:02 UTC, suvajit-sarkar commented
Hi @monar24 i think it will make more sense to put the Aries helm charts in https://github.com/hyperledger/bevel-samples under identity rather having under Bevel DLT platforms. Or maybe we put under Indy platform as an identity solution. ?

2024-02-05 18:20 UTC, monar24 commented
> https://github.com/hyperledger/bevel-samples



> Hi @monar24 i think it will make more sense to put the Aries helm charts in https://github.com/hyperledger/bevel-samples under identity rather having under Bevel DLT platforms. Or maybe we put under Indy platform as an identity solution. ?

Thanks everyone for the feedback and time reviewing. 

I actually agree with moving it to bevel-samples. Aries agents are deployed in order to interact with an underlying ledger, the ledger being indy by default mostly. Since bevel itself is for deploying the actual networks, I agree that it may be better to move these agent charts there. 

I have raised that PR here: https://github.com/hyperledger/bevel-samples/pull/78

2024-02-07 10:11 UTC, suvajit-sarkar commented
Closing this PR as we have moved to https://github.com/hyperledger/bevel-samples/pull/78

2024-02-07 10:11 UTC, closed without merging

2024-03-26 14:40 UTC, swcurran commented
Flagging @WadeBarnes about this contribution.