feat(besu): implement qbft_proposeValidatorVote  method to add or rem…
hyperledger/bevel pull request #2517
Opened 2024-02-26 15:56 UTC by saikumarbommakanti

…ove a node

Changes:

Introduced new helm chart named besu-propose-validator at path platforms/hyperledger-besu/charts/. This chart utilizes the qbft_proposeValidatorVote  method to facilitate the addition or removal of nodes from the validator set based on majority votes. fixes #2508

2024-02-27 10:24 UTC, suvajit-sarkar requested changes

2024-02-27 10:24 UTC, suvajit-sarkar commented on platforms/hyperledger-besu/charts/besu-propose-validator/templates/besu-propose-validator.yaml
> +                proposal_response=$(curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"qbft_proposeValidatorVote","params":["'"$propose_val_addr"'",{{ .Values.vali
this does not take care of other consensus

2024-02-28 11:10 UTC, suvajit-sarkar approved these changes
LGTM

2024-02-28 16:03 UTC, sownak approved these changes

2024-02-28 16:05 UTC, merged