[fabric] Introduce helm chart deployment capability for version 2.5
hyperledger/bevel pull request #2529
Opened 2024-03-20 08:11 UTC by mgCepeda

**Primary Changes**

1. This PR includes changes to deploy fabric 2.5.4 without a channel using helm charts.
2. Version 2.2.2 is pending
3. Deploy with Ansible pending

**Changes in charts**
platforms/hyperledger-fabric/charts/fabric-ca-server 
platforms/hyperledger-fabric/charts/fabric-cacerts-gen 
platforms/hyperledger-fabric/charts/fabric-catools 
platforms/hyperledger-fabric/charts/fabric-cli
platforms/hyperledger-fabric/charts/fabric-orderernode 
platforms/hyperledger-fabric/charts/fabric-peernode

fixes #2484

2024-03-20 11:38 UTC, sownak requested changes

2024-03-26 17:00 UTC, mgCepeda commented on platforms/hyperledger-fabric/charts/README.md
> +helm install supplychain-tools ./fabric-catools --namespace supplychain-net --values ./values/noproxy-and-novault/ordererOrganization/ca-tools-orderer.yaml
Done

2024-03-26 17:00 UTC, mgCepeda commented on platforms/hyperledger-fabric/charts/fabric-ca-server/values.yaml
>  proxy:
Done

2024-03-26 17:00 UTC, mgCepeda commented on platforms/hyperledger-fabric/charts/fabric-ca-server/values.yaml
> +  serviceType: ClusterIP
Done

2024-03-26 17:00 UTC, mgCepeda commented on platforms/hyperledger-fabric/charts/fabric-ca-server/values.yaml
>    name: ca
Done

2024-03-26 17:00 UTC, mgCepeda commented on platforms/hyperledger-fabric/charts/fabric-ca-server/templates/configmap.yaml
> +    app.kubernetes.io/name: {{ $.Values.server.name }}
Done

2024-03-26 17:00 UTC, mgCepeda commented on .gitignore
> +**/files/*.yaml
Done

2024-03-27 08:31 UTC, mgCepeda commented on platforms/hyperledger-fabric/charts/fabric-ca-server/README.md
> +| externalUrlSuffix   | External URL suffix for the organization                                 | org1proxy.blockchaincloudpoc.com    |
Done. Only the name of the variable was changed, not the value.

2024-03-27 10:25 UTC, sownak approved these changes

2024-04-01 06:42 UTC, suvajit-sarkar approved these changes
LGTM

2024-04-01 06:42 UTC, merged